language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build
  - cd webapp
  - ./gradlew test

notifications:
  email:
    recipients:
      - dantala.a@husky.neu.edu
      - patel.ankit@husky.neu.edu
      - shukla.ke@husky.neu.edu
    on_success: always
    on_failure: always
