language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./webapp/gradlew clean build

notifications:
  username:
    recipients:
      - dantala.a@husky.neu.edu
      - patel.ankit@husky.neu.edu
      - shukla.ke@husky.neu.edu
    on_success: always
