language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./webapp/gradlew build --info
  - cd webapp
  - ./gradlew test --info

notifications:
  username:
    recipients:
      - dantala.a@husky.neu.edu
      - patel.ankit@husky.neu.edu
      - shukla.ke@husky.neu.edu
    on_success: always
