language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - pwd
  - cd webapp
  - ./gradlew test
  - ./gradlew war
  - cd ..
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war app*.yml *.sh
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: $branch
  - provider: codedeploy
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $s3_bucket
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: $code_deploy_application
    deployment_group: $code_deploy_application
    wait-until-deployed: true
    on:
      branch: $branch

notifications:
  email:
    recipients:
      - dantala.a@husky.neu.edu
      - patel.ankit@husky.neu.edu
      - shukla.ke@husky.neu.edu
    on_success: always
    on_failure: always
