language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew build

notifications:
  username:
    recipients:
      - dantala.a@northeastern.edu
      - patel.ankit@northeastern.edu
      - shukla.ke@northeastern.edu

  slack: csye:Hvj830CZamSMtnkQAtXIDSZG
