language: java
jdk:
	- oraclejdk8

sudo: false
install: true

script:
	- ./gradlew war
	- ./gradlew build

notifications:
	username:
		recipients:
			- shukla.ke@husky.neu.edu
			- dantala.a@husky.neu.edu
			- patel.ankit@husky.neu.edu

    slack: csye:Hvj830CZamSMtnkQAtXIDSZG